bot:                             # Настройки бота
  env:                              # Переменные окружения
    token: TOKEN_BOT_IRON_SELLER       # Токен бота

logger:                          # Настройка логгеров проекта
  development_logger_level: DEBUG   # Уровень логгера для разработки
  business_logger_level: DEBUG      # Уровень логгера для бизнес логики

api:                             # Настройки взаимодействия с API
  shopper: http://90.156.168.154:5100/user
  order: http://90.156.168.154:5100/order
  category: http://90.156.168.154:5100/category
  product: http://90.156.168.154:5100/product
  authorization_url: http://90.156.168.154:5100/seller
  #shopper: # url для получения данных
  #order: # url для получения данных
  #category: # url для получения данных
  #product: # url для получения данных
  #authorization_url: # url для получения данных

seller_data:                    # Настройки для продавцов
  session_time: 1200                # Время сессии продавца

shopper_data:                   # Настройки для покупателей
    session_time: 5                # Время сессии покупателя

product_data:                   # Настройки для работы с данными о товарах
  update_period: 1800               # Период обновления данных о товарах
